const WHATSAPP='254780079982';
const img=(url,w=900,q=76)=>`https://wsrv.nl/?url=${encodeURIComponent(url)}&w=${w}&q=${q}&output=webp`;
const products=[
 {id:1,name:'Simba Cement 32.5R',price:550,description:'Reliable general-purpose cement for everyday construction.',original:'https://i.postimg.cc/MH7VkgNJ/Screenshot-2026-09-01-205350.png',image:img('https://i.postimg.cc/MH7VkgNJ/Screenshot-2026-09-01-205350.png',700)},
 {id:2,name:'Simba Power 42.5N',price:680,description:'High-strength cement for demanding structural work.',original:'https://i.postimg.cc/h4Qq8KWY/Screenshot-2026-09-01-205450.png',image:img('https://i.postimg.cc/h4Qq8KWY/Screenshot-2026-09-01-205450.png',700)},
 {id:3,name:'Paving Blocks (600mm)',price:650,description:'Durable paving blocks for driveways, walkways and outdoor construction.',original:'https://i.postimg.cc/y8QfrS09/Screenshot-2026-09-02-144841.png',image:img('https://i.postimg.cc/y8QfrS09/Screenshot-2026-09-02-144841.png',700)},
 {id:4,name:'Barbed Wire 240mts',price:1900,description:'Strong barbed wire for fencing, boundary protection and construction projects.',original:'https://i.postimg.cc/nLmvYs2x/Screenshot-2026-09-02-144319.png',image:img('https://i.postimg.cc/nLmvYs2x/Screenshot-2026-09-02-144319.png',700)},
 {id:5,name:'Barbed Wire 480mts',price:3400,description:'Long-length barbed wire for fencing, boundary protection and larger construction projects.',original:'https://i.postimg.cc/J7pBXc8d/Screenshot-2026-09-02-135758.png',image:img('https://i.postimg.cc/J7pBXc8d/Screenshot-2026-09-02-135758.png',700)},
 {id:6,name:'Barbed Wire 610mts',price:4200,description:'Long-length barbed wire for extensive fencing, boundary protection and larger construction projects.',original:'https://i.postimg.cc/9000bK28/Screenshot-2026-09-02-135513.png',image:img('https://i.postimg.cc/9000bK28/Screenshot-2026-09-02-135513.png',700)},
 {id:7,name:'Chainlink 4ft x 18mts',price:2000,description:'Durable chainlink fencing for boundaries, compounds and construction projects.',original:'https://i.postimg.cc/k4fFD0wf/Screenshot-2026-09-02-133720.png',image:img('https://i.postimg.cc/k4fFD0wf/Screenshot-2026-09-02-133720.png',700)},
 {id:8,name:'Chainlink 5ft x 18mts',price:2500,description:'Durable chainlink fencing for taller boundaries, compounds and construction projects.',original:'https://i.postimg.cc/k4fFD0wf/Screenshot-2026-09-02-133720.png',image:img('https://i.postimg.cc/k4fFD0wf/Screenshot-2026-09-02-133720.png',700)},
 {id:9,name:'Chainlink 6ft x 18mts',price:3000,description:'Durable chainlink fencing for taller boundaries, compounds and construction projects.',original:'https://i.postimg.cc/k4fFD0wf/Screenshot-2026-09-02-133720.png',image:img('https://i.postimg.cc/k4fFD0wf/Screenshot-2026-09-02-133720.png',700)},
 {id:10,name:'Chainlink 7ft x 18mts',price:3500,description:'Durable chainlink fencing for tall boundaries, compounds and construction projects.',original:'https://i.postimg.cc/k4fFD0wf/Screenshot-2026-09-02-133720.png',image:img('https://i.postimg.cc/k4fFD0wf/Screenshot-2026-09-02-133720.png',700)}
];
let cart=JSON.parse(localStorage.getItem('simbaCementOfficialCart')||'[]');
const money=n=>n?'KES '+n.toLocaleString():'Quote';
function renderProducts(){const grid=document.getElementById('productGrid');if(!grid)return;grid.innerHTML=products.map(p=>`<article class="product"><div class="product-image">${p.image?`<img src="${p.image}" alt="${p.name}" loading="lazy" decoding="async" fetchpriority="low" width="700" height="500" onerror="if(!this.dataset.fallback){this.dataset.fallback='1';this.src='${p.original}'}else{this.style.display='none'}">`:'<div class="bag">SIMBA<br>CEMENT</div>'}</div><h3>${p.name}</h3><p>${p.description}</p><div class="price">${money(p.price)}</div><button class="add" onclick="addToCart(${p.id})">${p.price?'Add to Cart':'Request Quote'}</button></article>`).join('')}
function save(){localStorage.setItem('simbaCementOfficialCart',JSON.stringify(cart));renderCart();}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p.price){window.open('https://wa.me/'+WHATSAPP+'?text='+encodeURIComponent('Hello Simba Cement Kenya, I would like a quotation for '+p.name+'.'),'_blank');return}const item=cart.find(x=>x.id===id);item?item.qty++:cart.push({id,qty:1});save();openCart()}
function changeQty(id,delta){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=delta;if(x.qty<1)cart=cart.filter(i=>i.id!==id);save()}
function removeItem(id){cart=cart.filter(i=>i.id!==id);save()}
function renderCart(){const countEl=document.getElementById('cartCount'),box=document.getElementById('cartItems'),totalEl=document.getElementById('cartTotal');if(!countEl||!box||!totalEl)return;const count=cart.reduce((a,x)=>a+x.qty,0);countEl.textContent=count;if(!cart.length){box.innerHTML='<p style="color:#777;padding:30px 0">Your cart is empty. Add products to begin.</p>';totalEl.textContent='KES 0';return}let total=0;box.innerHTML=cart.map(x=>{const p=products.find(q=>q.id===x.id),sub=p.price*x.qty;total+=sub;return `<div class="cart-item"><div><h4>${p.name}</h4><div>${money(p.price)} each</div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${x.qty}</b><button onclick="changeQty(${p.id},1)">+</button></div></div><div><strong>${money(sub)}</strong><br><button class="remove" onclick="removeItem(${p.id})">Remove</button></div></div>`}).join('');totalEl.textContent=money(total)}
function openCart(){document.getElementById('cartPanel').classList.add('open');document.getElementById('cartPanel').setAttribute('aria-hidden','false');renderCart()}
function closeCart(){document.getElementById('cartPanel').classList.remove('open');document.getElementById('cartPanel').setAttribute('aria-hidden','true')}
function checkout(e){e.preventDefault();if(!cart.length){alert('Please add at least one product to your cart.');return}const name=document.getElementById('customerName').value.trim(),phone=document.getElementById('customerPhone').value.trim(),location=document.getElementById('deliveryLocation').value.trim(),notes=document.getElementById('orderNotes').value.trim();let total=0;const lines=cart.map(x=>{const p=products.find(q=>q.id===x.id),sub=p.price*x.qty;total+=sub;return `• ${p.name} — ${x.qty} × ${money(p.price)} = ${money(sub)}`});const ref='SC-'+Date.now().toString().slice(-7);const msg=`Hello Simba Cement Kenya!%0A%0A*NEW ORDER ${ref}*%0A${lines.join('%0A')}%0A%0A*TOTAL: ${money(total)}*%0A%0A*Customer details*%0AName: ${encodeURIComponent(name)}%0APhone: ${encodeURIComponent(phone)}%0ADelivery location: ${encodeURIComponent(location)}%0ANotes: ${encodeURIComponent(notes||'None')}%0A%0APlease confirm availability and delivery.`;window.open(`https://wa.me/${WHATSAPP}?text=${msg}`,'_blank')}
function submitReview(e){e.preventDefault();const name=document.getElementById('reviewName').value.trim();const box=document.getElementById('reviewThankYou');box.innerHTML=`<strong>Thank you, ${name || 'for your'}!</strong><br>Your review has been received. We appreciate you taking the time to share your experience.`;box.classList.add('show');e.target.reset();}
const heroFallbacks=['https://i.postimg.cc/9X162sBR/Screenshot-2026-09-01-205904.png','https://i.postimg.cc/SxVdYpJD/Screenshot-2026-09-01-205620.png','https://i.postimg.cc/bvWQ1Y82/Screenshot-2026-09-01-205703.png'];
let heroSlideIndex=0;let heroTimer;
function loadHeroImage(index){const slides=document.querySelectorAll('.hero-slide');if(!slides.length)return;const slide=slides[index];if(!slide||slide.dataset.loaded)return;slide.dataset.loaded='1';const optimized=slide.dataset.bg;const fallback=heroFallbacks[index];const tester=new Image();tester.onload=()=>{slide.style.backgroundImage=`url("${optimized}")`};tester.onerror=()=>{slide.style.backgroundImage=`url("${fallback}")`};tester.src=optimized}
function showHeroSlide(index){const slides=document.querySelectorAll('.hero-slide');const dots=document.querySelectorAll('.hero-dot');if(!slides.length)return;heroSlideIndex=(index+slides.length)%slides.length;loadHeroImage(heroSlideIndex);loadHeroImage((heroSlideIndex+1)%slides.length);slides.forEach((s,i)=>s.classList.toggle('active',i===heroSlideIndex));dots.forEach((d,i)=>d.classList.toggle('active',i===heroSlideIndex))}
function goHeroSlide(index){showHeroSlide(index);restartHeroTimer()}
function changeHeroSlide(delta){showHeroSlide(heroSlideIndex+delta);restartHeroTimer()}
function restartHeroTimer(){clearInterval(heroTimer);heroTimer=setInterval(()=>showHeroSlide(heroSlideIndex+1),6000)}
function fixAboutImage(){const about=document.querySelector('.about-photo');if(!about)return;const fallback='https://i.postimg.cc/9QZkzf9P/Screenshot-2026-09-01-205904.png';about.addEventListener('error',()=>{if(!about.dataset.fallback){about.dataset.fallback='1';about.src=fallback}});}
renderProducts();renderCart();fixAboutImage();showHeroSlide(0);restartHeroTimer();
