const WHATSAPP='254780079982';
const products=[
 {id:1,name:'Simba Cement 32.5R',price:550,description:'Reliable general-purpose cement for everyday construction.',image:'https://i.postimg.cc/MH7VkgNJ/Screenshot-2026-09-01-205350.png'},
 {id:2,name:'Simba Power 42.5N',price:680,description:'High-strength cement for demanding structural work.',image:'https://i.postimg.cc/h4Qq8KWY/Screenshot-2026-09-01-205450.png'},
 {id:3,name:'Paving Blocks (600mm)',price:650,description:'Durable paving blocks for driveways, walkways and outdoor construction.',image:'https://i.postimg.cc/y8QfrS09/Screenshot-2026-09-02-144841.png'},
 {id:4,name:'Barbed Wire 240mts',price:1900,description:'Strong barbed wire for fencing, boundary protection and construction projects.',image:'https://i.postimg.cc/nLmvYs2x/Screenshot-2026-09-02-144319.png'},
 {id:5,name:'Barbed Wire 480mts',price:3400,description:'Long-length barbed wire for fencing, boundary protection and larger construction projects.',image:'https://i.postimg.cc/J7pBXc8d/Screenshot-2026-09-02-135758.png'},
 {id:6,name:'Barbed Wire 610mts',price:4200,description:'Long-length barbed wire for extensive fencing, boundary protection and larger construction projects.',image:'https://i.postimg.cc/9000bK28/Screenshot-2026-09-02-135513.png'},
 {id:7,name:'Chainlink 4ft x 18mts',price:2000,description:'Durable chainlink fencing for boundaries, compounds and construction projects.',image:'https://i.postimg.cc/k4fFD0wf/Screenshot-2026-09-02-133720.png'},
 {id:8,name:'Chainlink 5ft x 18mts',price:2500,description:'Durable chainlink fencing for taller boundaries, compounds and construction projects.',image:'https://i.postimg.cc/k4fFD0wf/Screenshot-2026-09-02-133720.png'},
 {id:9,name:'Chainlink 6ft x 18mts',price:3000,description:'Durable chainlink fencing for taller boundaries, compounds and construction projects.',image:'https://i.postimg.cc/k4fFD0wf/Screenshot-2026-09-02-133720.png'},
 {id:10,name:'Chainlink 7ft x 18mts',price:3500,description:'Durable chainlink fencing for tall boundaries, compounds and construction projects.',image:'https://i.postimg.cc/k4fFD0wf/Screenshot-2026-09-02-133720.png'}
];
const imageFallbacks={};
function imageError(img){img.style.display='none'}
let cart=JSON.parse(localStorage.getItem('simbaCementOfficialCart')||'[]');
const money=n=>n?'KES '+n.toLocaleString():'Quote';
function renderProducts(){const grid=document.getElementById('productGrid');if(!grid)return;grid.innerHTML=products.map(p=>`<article class="product"><div class="product-image ${p.id===5||p.id===6?'product-image-wire':''}"><img src="${p.image}" alt="${p.name}" loading="eager" decoding="async" onerror="imageError(this)"></div><h3>${p.name}</h3><p>${p.description}</p><div class="price">${money(p.price)}</div><button class="add" onclick="addToCart(${p.id})">Add to Cart</button></article>`).join('')}
function save(){localStorage.setItem('simbaCementOfficialCart',JSON.stringify(cart));renderCart();}
function addToCart(id){const p=products.find(x=>x.id===id);const item=cart.find(x=>x.id===id);item?item.qty++:cart.push({id,qty:1});save();openCart()}
function changeQty(id,delta){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=delta;if(x.qty<1)cart=cart.filter(i=>i.id!==id);save()}
function removeItem(id){cart=cart.filter(i=>i.id!==id);save()}
function renderCart(){const countEl=document.getElementById('cartCount'),box=document.getElementById('cartItems'),totalEl=document.getElementById('cartTotal');if(!countEl||!box||!totalEl)return;const count=cart.reduce((a,x)=>a+x.qty,0);countEl.textContent=count;if(!cart.length){box.innerHTML='<p style="color:#777;padding:30px 0">Your cart is empty. Add products to begin.</p>';totalEl.textContent='KES 0';return}let total=0;box.innerHTML=cart.map(x=>{const p=products.find(q=>q.id===x.id),sub=p.price*x.qty;total+=sub;return `<div class="cart-item"><div><h4>${p.name}</h4><div>${money(p.price)} each</div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${x.qty}</b><button onclick="changeQty(${p.id},1)">+</button></div></div><div><strong>${money(sub)}</strong><br><button class="remove" onclick="removeItem(${p.id})">Remove</button></div></div>`}).join('');totalEl.textContent=money(total)}
function openCart(){document.getElementById('cartPanel').classList.add('open');document.getElementById('cartPanel').setAttribute('aria-hidden','false');renderCart()}
function closeCart(){document.getElementById('cartPanel').classList.remove('open');document.getElementById('cartPanel').setAttribute('aria-hidden','true')}
function checkout(e){e.preventDefault();if(!cart.length){alert('Please add at least one product to your cart.');return}const name=document.getElementById('customerName').value.trim(),phone=document.getElementById('customerPhone').value.trim(),location=document.getElementById('deliveryLocation').value.trim(),notes=document.getElementById('orderNotes').value.trim();let total=0;const lines=cart.map(x=>{const p=products.find(q=>q.id===x.id),sub=p.price*x.qty;total+=sub;return `• ${p.name} — ${x.qty} × ${money(p.price)} = ${money(sub)}`});const ref='SC-'+Date.now().toString().slice(-7);const msg=`Hello Simba Cement Kenya!%0A%0A*NEW ORDER ${ref}*%0A${lines.join('%0A')}%0A%0A*TOTAL: ${money(total)}*%0A%0A*Customer details*%0AName: ${encodeURIComponent(name)}%0APhone: ${encodeURIComponent(phone)}%0ADelivery location: ${encodeURIComponent(location)}%0ANotes: ${encodeURIComponent(notes||'None')}%0A%0APlease confirm availability and delivery.`;window.open(`https://wa.me/${WHATSAPP}?text=${msg}`,'_blank')}
function submitReview(e){e.preventDefault();const name=document.getElementById('reviewName').value.trim();const box=document.getElementById('reviewThankYou');box.innerHTML=`<strong>Thank you, ${name || 'for your'}!</strong><br>Your review has been received. We appreciate you taking the time to share your experience.`;box.classList.add('show');e.target.reset();}
function renderHero(){const slides=document.querySelectorAll('.hero-slide');const dots=document.querySelectorAll('.hero-dot');if(!slides.length)return;let index=0;const show=()=>{slides.forEach((s,i)=>s.classList.toggle('active',i===index));dots.forEach((d,i)=>d.classList.toggle('active',i===index));slides[index].style.backgroundImage=`url("${slides[index].dataset.bg}")`;index=(index+1)%slides.length};show();setInterval(show,6000)}
function goHeroSlide(index){const slides=document.querySelectorAll('.hero-slide');const dots=document.querySelectorAll('.hero-dot');if(!slides.length)return;slides.forEach((s,i)=>{s.classList.toggle('active',i===index);if(i===index)s.style.backgroundImage=`url("${s.dataset.bg}")`});dots.forEach((d,i)=>d.classList.toggle('active',i===index))}
function fixAboutImage(){const about=document.querySelector('.about-photo');if(!about)return;about.addEventListener('error',()=>{about.style.display='none'})}
renderProducts();renderCart();fixAboutImage();renderHero();
